# Generated by Django 2.2 on 2019-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=20, verbose_name='模板名称')),
                ('template_detail', models.TextField(max_length=1000)),
                ('refer_data', models.CharField(max_length=20)),
                ('upper_tempname', models.CharField(max_length=20)),
                ('report_id', models.IntegerField(max_length=4)),
            ],
            options={
                'verbose_name': '模板数据',
                'verbose_name_plural': '模板数据',
            },
        ),
    ]
