# Generated by Django 2.2 on 2019-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie_name', models.CharField(max_length=20, verbose_name='饼图名称')),
                ('pie_detail', models.TextField(max_length=1000)),
                ('pie_date', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '饼图数据',
                'verbose_name_plural': '饼图数据',
            },
        ),
    ]
