# Generated by Django 2.2 on 2019-08-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_piedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='piedata',
            name='pie_t1',
            field=models.CharField(default='title', max_length=20),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_t2',
            field=models.CharField(default='title', max_length=20),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_t3',
            field=models.CharField(default='title', max_length=20),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_v1',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_v2',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_v3',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
