# Generated by Django 2.2 on 2019-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20190807_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='piedata',
            name='pie_left',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_title',
            field=models.CharField(default='这里是图表标题', max_length=80),
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_top',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
