# Generated by Django 2.2 on 2019-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_piedata_pie_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piedata',
            name='pie_left',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='piedata',
            name='pie_size',
            field=models.FloatField(default=50, max_length=4),
        ),
        migrations.AlterField(
            model_name='piedata',
            name='pie_top',
            field=models.FloatField(default=0, max_length=4),
        ),
    ]
