# Generated by Django 2.2 on 2019-08-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20190814_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=20, verbose_name='报告名称')),
                ('report_note', models.TextField(max_length=1000, verbose_name='备注')),
                ('report_date', models.CharField(max_length=20, verbose_name='创建日期')),
                ('report_creator', models.CharField(max_length=20, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
            },
        ),
        migrations.AddField(
            model_name='piedata',
            name='pie_report_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Report', verbose_name='所属报告'),
        ),
    ]
