# Generated by Django 2.2 on 2019-08-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20190819_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piedata',
            old_name='pie_report_id',
            new_name='pie_report',
        ),
    ]
