# Generated by Django 2.2 on 2019-08-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20190819_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_creator',
            field=models.CharField(default='1', max_length=20, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.CharField(default='2019-08-10', max_length=20, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(default='未查看报告', max_length=20, verbose_name='报告名称'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_note',
            field=models.TextField(default='这里是备注', max_length=1000, verbose_name='备注'),
        ),
    ]
