# Generated by Django 2.2 on 2019-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20190819_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_chack',
            field=models.BooleanField(default=False, verbose_name='是否已被查看'),
        ),
    ]
