# Generated by Django 2.2 on 2019-07-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '数据库测试', 'verbose_name_plural': '数据库测试'},
        ),
    ]
